import { AxiosResponse } from 'axios';

export enum StatusCode {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export enum ErrorMessage {
  BAD_ACCESS_TOKEN = 'BAD_ACCESS_TOKEN',
  BAD_REFRESH_TOKEN = 'BAD_REFRESH_TOKEN',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  ACCOUNT_EXPIRED = 'ACCOUNT_EXPIRED',
  RECENT_PASSWORDS_MATCH = 'RECENT_PASSWORDS_MATCH',
  PASSWORD_MIN_LENGTH_DOES_NOT_MATCH = 'PASSWORD_MIN_LENGTH_DOES_NOT_MATCH',
  PASSWORD_COMPLEXITY_DOES_NOT_MATCH = 'PASSWORD_COMPLEXITY_DOES_NOT_MATCH',
  PASSWORD_CONTAINS_USERNAME = 'PASSWORD_CONTAINS_USERNAME',
  BAD_RESET_PASSWORD_TOKEN = 'BAD_RESET_PASSWORD_TOKEN',
}

export interface IApiResponse extends AxiosResponse {
  error: Error;
}
